import "./globals.css";
import Providers from "@/components/Providers";

export const metadata = {
  title: "iMovie - Find your all movies here",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          {children}
        </Providers>

      </body>
    </html>
  );
}
